#define TRX_DEVICE_STATUS   0
#define TRX_DEVICE_START    1
#define TRX_DEVICE_ABORT    2
#define TRX_DEVICE_ADD      3
#define TRX_DEVICE_MODIFY   4
#define TRX_DEVICE_DELETE   5
#define TRX_DEVICE_ONLINE   6
#define TRX_DEVICE_OFFLINE  7
#define TRX_CLIENT_IDENTIFY 8


#define TRX_MAIL_SEND_MSG  20
#define TRX_MAIL_RECV_MSG  21
#define TRX_MAIL_RECV_ACK  22
#define TRX_MAIL_SEND_ACK  23

#define TRX_CONSULTOR_QUERY      24
#define TRX_CONSULTOR_STATUS    25
#define TRX_CONSULTOR_OFFLINE   26
#define TRX_CONSULTOR_DETECT    27

#define TRX_EXECUTE_PROCESS_QUERY	 30
#define TRX_PROCESS_ALARM            32
#define TRX_MENSAJE_COLA             33


#define TRX_EXECUTE_PROCESS_QUERY_NOANSWER	  42


#define TRX_MAILSERVER_MAIL_RULE	  50
#define TRX_MAILSERVER_UPDATE_RULES   51
#define TRX_MAILSERVER_MAIL_GENERIC   52

#define TRX_PAGERSERVER_UPDATE_RULES  51
#define TRX_PAGERSERVER_PAGER_RULE    50

#define TRX_QUERY_COM_STATUS		  60
#define TRX_MENSAJE_PROCESOS          99